In [89]:
import torch
import numpy as np
print(torch.__version__)

2.0.1+cu117


## TENSORS

In [90]:
tensor_data = torch.tensor([1,2,3])  # tensor is a numerical representation
print(tensor_data)

tensor([1, 2, 3])


In [91]:
tensor_data = torch.tensor([1,2,3],dtype=torch.float64)  # requires_grad=False , pin_memory=False  , device=torch.device('cuda:0') or device = "cuda" or "cpu"
print(tensor_data)

#Arrays can have varying dimensions, but don't inherently represent scalars, vectors, or matrices	
# Tensors encompass scalars, vectors, and matrices as special cases

tensor([1., 2., 3.], dtype=torch.float64)


In [92]:
tensor_data.ndim

1

In [93]:
#  tensor_data.item()  # only for scalar data
tensor_data.shape  # (3,1)

torch.Size([3])

In [94]:
t3D_tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

print(t3D_tensor)

print(t3D_tensor.shape)


print(t3D_tensor.ndim)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
torch.Size([1, 3, 3])
3


 PIN MEMORY  ---- 
 
 the pin_memory parameter is typically used in the data loading process when working with DataLoader objects. When pin_memory is set to True, it enables the data to be directly transferred to the GPU memory (if available) from the host memory (RAM) during the data loading process. This can potentially speed up the data transfer between CPU and GPU, leading to faster training times.

However, when pin_memory is set to True, it also consumes additional CPU memory, as it creates a pinned memory buffer to facilitate the data transfer. This may not be an issue if the system has sufficient RAM to spare.

If you set pin_memory to False, it means that the data will not be directly transferred to the GPU memory during data loading. Instead, it will stay in the host memory (RAM) and will be transferred to the GPU on-the-fly during the training process. This could result in slightly slower data transfer times between CPU and GPU, but it reduces the additional memory overhead on the CPU.

AUTOGRAD   --- 

Instead, autograd is a fundamental feature of PyTorch that is always enabled by default. It is responsible for automatic differentiation, which is a key component of training neural networks through backpropagation.

Automatic differentiation is a technique that allows the framework to automatically compute gradients of the loss function with respect to all the learnable parameters in the model. Gradients represent the direction and magnitude of the steepest increase of the loss function with respect to each parameter, which is used to update the parameters during training and minimize the loss.

When autograd is set to True, PyTorch keeps track of all the operations performed on tensors (inputs, activations, etc.) that are involved in calculating the loss. This creates a computational graph, which is used to compute the gradients when you call the backward() method on the loss tensor. This process propagates the gradients backward through the network and computes the gradients for each parameter.

In summary, autograd=True is the default behavior in PyTorch, and it is crucial for enabling automatic differentiation, which is essential for training deep learning models using gradient-based optimization techniques like stochastic gradient descent (SGD) or Adam.

You can think of autograd as the engine that powers the automatic computation of gradients, making it easier for developers to define and train complex neural network architectures without having to derive and implement gradients manually for each parameter.

## NUMEL

In [95]:
a = torch.randn(1,2,3,4)
print(a.shape)
numel_data = torch.numel(a)  # calculates total number of elements in the data matrix
print(numel_data)

torch.Size([1, 2, 3, 4])
24


## RANDOM

In [96]:
random_tensors = torch.rand(5)
print(random_tensors)

tensor([0.4626, 0.7164, 0.7406, 0.6282, 0.9490])


In [97]:
r2 = torch.rand(3,4)
print(r2)
print(r2.shape)

tensor([[0.1778, 0.7985, 0.3029, 0.1362],
        [0.1322, 0.7722, 0.2843, 0.1168],
        [0.4158, 0.8765, 0.5435, 0.0484]])
torch.Size([3, 4])


In [98]:
r3 = torch.rand(3,224,224) # image type
print(r3.ndim)

3


Initialization in Neural Networks: 

In deep learning, random tensors are often used for weight initialization in neural networks. Proper initialization can significantly impact the training process, leading to faster convergence and better generalization. Random initialization helps avoid symmetry issues and ensures that neurons start with diverse initial weights, which can improve learning efficiency.

Data Augmentation: 

Random tensors are employed in data augmentation techniques to increase the size and diversity of training datasets. By applying random transformations to input data (e.g., rotations, translations, flips), the model becomes more robust and better at generalizing to unseen examples.

In [99]:
zero_tensor = torch.zeros(3,3)
print(zero_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [100]:
torch.arange(1,20)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19])

In [101]:
torch.arange(1,8,3)

tensor([1, 4, 7])

In [102]:
torch.zeros_like(input = torch.arange(1, 4))

tensor([0, 0, 0])

# CONVERT FLOAT 32 TO FLOAT 16

In [103]:
float32_tensor = torch.tensor([1.0,2.0,3.0],dtype = None,device = "cpu",requires_grad=False)
print(float32_tensor.dtype)

torch.float32


In [104]:
float16_tensor = float32_tensor.type(torch.float16)

In [105]:
print(float16_tensor.dtype)

torch.float16


In [106]:
# precision in computing

we can multiply in32 with float32 result is float32

tensors errors are --  (tensor attributes)

1.tensor shape 

2.tensor device 

3.tensor dtype

In [107]:
torch.mul(torch.tensor([1,2,3]),4)

tensor([ 4,  8, 12])

In [108]:
torch.add(torch.tensor([1,2,3]),4)

tensor([5, 6, 7])

ELEMENT WISE MULTIPLICATION

MATRIX MULTIPLICATION (DOT PRODUCT)

In [109]:
t = torch.tensor([1,2,3,4])
print(t*t)

tensor([ 1,  4,  9, 16])


In [110]:
t1 = torch.tensor([[1,2,3,4],[6,7,8,9]])
print(t1*t1)

tensor([[ 1,  4,  9, 16],
        [36, 49, 64, 81]])


In [111]:
print(t1*t)

tensor([[ 1,  4,  9, 16],
        [ 6, 14, 24, 36]])


In [112]:
%%time
torch.matmul(t1,t)  # rather than for loops it is faster

CPU times: user 156 µs, sys: 31 µs, total: 187 µs
Wall time: 178 µs


tensor([30, 80])

In [113]:
%%time
print(t1.ndim)
print(t1.shape)

2
torch.Size([2, 4])
CPU times: user 125 µs, sys: 0 ns, total: 125 µs
Wall time: 84.9 µs


In [114]:
t.T

tensor([1, 2, 3, 4])

find min and max and sum of tensor

In [115]:
torch.min(t1)

tensor(1)

In [116]:
t1.max()
    

t2 = t1.type(torch.float32)

In [117]:
torch.mean(t2)  # mean only for floats or complex types

tensor(5.)

In [118]:
t2.mean()

tensor(5.)

In [119]:
t2.sum()

tensor(40.)

In [120]:
t2.std()

tensor(2.9277)

In [121]:
t2.argmin()

tensor(0)

In [122]:
t2.argmax() # find position of max element

tensor(7)

# reshaping , stacking, squeezing , unsqueezing , view , permute

Reshaping: Changing the shape (dimensions) of a tensor while keeping the total number of elements unchanged.

Stacking: Combining tensors along a new dimension (axis) to create a new tensor.

Squeezing: Removing dimensions with size 1 from a tensor, effectively reducing its rank.

Unsqueezing: Adding dimensions with size 1 to a tensor, effectively increasing its rank.

View: A method to reshape a tensor while sharing the same data. It creates a new view of the tensor without changing its memory layout.

Permute: Rearranging the dimensions of a tensor by permuting its axes, allowing for different tensor manipulations without changing the data.

In [123]:
x = torch.arange(1.0,10.0)

In [124]:
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [125]:
x.reshape(1,9)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [126]:
x.reshape(9,1)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [127]:
y = torch.rand(2,3,4)

In [128]:
y

tensor([[[5.8882e-01, 1.2898e-01, 4.6408e-01, 3.0542e-01],
         [6.4682e-01, 3.4107e-01, 2.5581e-01, 7.1201e-01],
         [2.4293e-01, 1.0380e-01, 9.2764e-01, 4.7837e-01]],

        [[5.5024e-01, 8.4162e-05, 5.2151e-01, 6.6397e-03],
         [2.2366e-01, 1.4404e-01, 2.4611e-01, 3.7169e-01],
         [4.4611e-01, 2.7699e-01, 5.2093e-01, 3.2688e-01]]])

In [129]:
y.reshape(2,12)

tensor([[5.8882e-01, 1.2898e-01, 4.6408e-01, 3.0542e-01, 6.4682e-01, 3.4107e-01,
         2.5581e-01, 7.1201e-01, 2.4293e-01, 1.0380e-01, 9.2764e-01, 4.7837e-01],
        [5.5024e-01, 8.4162e-05, 5.2151e-01, 6.6397e-03, 2.2366e-01, 1.4404e-01,
         2.4611e-01, 3.7169e-01, 4.4611e-01, 2.7699e-01, 5.2093e-01, 3.2688e-01]])

In [130]:
y.reshape(1,24)

tensor([[5.8882e-01, 1.2898e-01, 4.6408e-01, 3.0542e-01, 6.4682e-01, 3.4107e-01,
         2.5581e-01, 7.1201e-01, 2.4293e-01, 1.0380e-01, 9.2764e-01, 4.7837e-01,
         5.5024e-01, 8.4162e-05, 5.2151e-01, 6.6397e-03, 2.2366e-01, 1.4404e-01,
         2.4611e-01, 3.7169e-01, 4.4611e-01, 2.7699e-01, 5.2093e-01, 3.2688e-01]])

view and reshape are same but view share same memory space with input x and z so change in z also change in x



In [131]:
z = x.view(1,9)
z , z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [132]:
z[:4] = 5
z,x

(tensor([[5., 5., 5., 5., 5., 5., 5., 5., 5.]]),
 tensor([5., 5., 5., 5., 5., 5., 5., 5., 5.]))

In [133]:
torch.stack([x,x],dim = 0)

tensor([[5., 5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [134]:
torch.stack([x,x],dim = 1)

tensor([[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]])

torch.vstack is dim =0, torch.hstack dim = 1

In [135]:
torch.squeeze(z)

tensor([5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [144]:
x1 = torch.zeros(2,1,3)
x1,x1.shape

(tensor([[[0., 0., 0.]],
 
         [[0., 0., 0.]]]),
 torch.Size([2, 1, 3]))

In [137]:
x2 = torch.squeeze(x1)
x2,x2.size()

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 torch.Size([2, 3]))

In [138]:
x2

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [139]:
x

tensor([5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [140]:
xr = x.reshape(1,9)
xr

tensor([[5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [141]:
xr.squeeze()

tensor([5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [142]:
xr.squeeze().shape

torch.Size([9])

In [143]:
x3 = xr.squeeze()
x3.unsqueeze(dim = 0) # (1,9)
x3.unsqueeze(dim = 1) # (9,1)


tensor([[5.],
        [5.],
        [5.],
        [5.],
        [5.],
        [5.],
        [5.],
        [5.],
        [5.]])

In [146]:
torch.permute(x1,(0,2,1))

tensor([[[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]]])